# Generated by Django 5.1 on 2024-09-08 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_posts_categories_posts_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.category'),
        ),
    ]
